version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@2

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - run: echo "WE'RE STARTING INSTALLING NPM"
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm install
      - run: node .circleci/deploy.js
      - run: echo "WE'RE ONLINE"

workflows:
  sample:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
      - cypress/run

      
